### ISSUE TITLE
Cross: Version packages in a cleverer way

### ISSUE THREAD

**Issue by guypritchard** [buerokratt/Cross-functional-requirements#56]
This is technical story which aims to get into the thorny issue of versioning.

Currently we have a nuget package which uses very simple versioning indeed (Major Version hard coded and the patch version coming from the build number).

There are many other ways to tackle versioning:

Semantic versioning.
Tagging the source code to indicate which version that code actually built.
Debug or prerelease versions of the package.

Note.  This versioning scheme doesn't just apply to the nuget package but each service should have a version baked in to allow for easier observability.

> Note: Look into Git hash for version

### Acceptance Criteria

- [x] Investigate Semantic Versioning (https://semver.org/)
- [ ] Investigate using git tags for tracking version numbers
- [x] Pre-release channel for the nuget package.
- [ ] Make an entry into the docs for the agreed versioning approach

**Comment by martinkearn** [comment]
@guypritchard @shelabd @turnerrainer Can we re-consider the priority of this ticket? As I write, it is set as P2, but it feels like it could be P3 because the outcome does not affect the functionality of the solution (the current versioning system works fine). If there is a reason it is P2, that is fine but can we discuss it at the next planning session?
